name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
      - release
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Установка зависимостей
        run: |
          pip install pytest  # Установка pytest

      - name: Запуск тестов
        run: |
          python -m pytest  # Запуск тестов

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Деплой приложения
        run: echo "Развертывание приложения..."